# Generated by Django 4.1.2 on 2022-10-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=255)),
                ("has_nightvision", models.BooleanField(default=False)),
            ],
        ),
    ]
