# Generated by Django 4.1.2 on 2022-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pictures",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="static/mysite/images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("Outdoors", "Outdoors"), ("Indoors", "Indoors")],
                max_length=255,
            ),
        ),
    ]
