# Generated by Django 4.1.2 on 2022-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_pictures_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pictures",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="cameras"
            ),
        ),
    ]
