# Generated by Django 4.1.2 on 2022-10-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("Outdoors", "Outdoors"),
                    ("Indoors", "Indoors"),
                    ("Universal", "Universal"),
                ],
                max_length=255,
            ),
        ),
    ]
